# Generated by Django 4.1.1 on 2022-09-12 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=20)),
                ('birthday', models.DateField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaAPI.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaAPI.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('familiar', models.AutoField(primary_key=True, serialize=False)),
                ('parentesco', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaAPI.paciente')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaAPI.persona')),
            ],
        ),
    ]
