# Generated by Django 4.1.1 on 2022-09-12 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaAPI', '0002_paciente_medico_familiar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='familiar',
            old_name='familiar',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='medico',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaAPI.paciente'),
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('signosVitales', models.BigIntegerField(default='125')),
                ('diagnostico', models.CharField(max_length=100)),
                ('sugerencia', models.CharField(max_length=50)),
                ('historiaClinica', models.CharField(max_length=255)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaAPI.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='JefeEnfermeria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaAPI.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='EnfermeroAuxiliar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicaAPI.paciente')),
            ],
        ),
    ]
