# Generated by Django 4.1.1 on 2022-09-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaAPI', '0003_rename_familiar_familiar_id_alter_medico_paciente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='signosVitales',
            field=models.BigIntegerField(),
        ),
    ]
