# Generated by Django 4.1.1 on 2022-09-12 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaAPI', '0005_medico_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfermeroauxiliar',
            name='registro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clinicaAPI.registro'),
        ),
        migrations.AddField(
            model_name='jefeenfermeria',
            name='registro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clinicaAPI.registro'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='registro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clinicaAPI.registro'),
        ),
    ]
