# Generated by Django 4.1.1 on 2022-09-12 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaAPI', '0007_enfermeroauxiliar_persona_jefeenfermeria_persona_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='signosVitales',
            field=models.IntegerField(),
        ),
    ]
