# Generated by Django 4.1.1 on 2022-09-12 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaAPI', '0009_remove_registro_signosvitales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='longitude',
            new_name='longitud',
        ),
    ]
