# Generated by Django 4.1.1 on 2022-09-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaAPI', '0012_alter_medico_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='registro',
            field=models.BigIntegerField(),
        ),
    ]
