# Generated by Django 4.1.1 on 2022-09-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaAPI', '0014_remove_enfermeroauxiliar_registro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medico',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
