# Generated by Django 4.1.1 on 2022-09-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaAPI', '0015_alter_familiar_id_alter_medico_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='paciente',
        ),
        migrations.AddField(
            model_name='medico',
            name='especialidad',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
