# Generated by Django 4.1.1 on 2022-09-28 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinicaAPI', '0018_enfermeroauxiliar_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enfermeroauxiliar',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
